{{- $fullDnsUniqueName := printf "%s.%s" .Values.tls.uniqueDnsName .Values.tls.uniqueDnsNameDomain -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: {{ template "certFullName" . }}
  namespace: istio-system
  labels:
    {{- include "istio-gateway.labels" $ | nindent 4 }}
spec:
  secretName: {{ template "certSecretName" $ }}  
  issuerRef:    
    name: {{ $.Values.certManager.issuer }}
    kind: ClusterIssuer
  commonName: {{ $fullDnsUniqueName | quote }}
  dnsNames:
    - {{ $fullDnsUniqueName | quote }}
    {{- range $dnsName := .Values.tls.domains }}
    - {{ $dnsName | quote }}
    {{- end }}