name: Build standard planday dockerfile

on:
  pull_request_review:
    types: [submitted,edited]
  push:
    branches:
      - "!main"
      - "!master"
  workflow_call:
    inputs:
      image_name:
        description: "name of the docker image that will be built"
        required: true
        type: string
      registry: 
        type: string
        description: "Azure Containers Registry to push the image to"
        required: true
      registrydev: 
        type: string
        description: "Azure dev Containers Registry to pull base images from"
        required: true
      version:
        type: string
        required: true
      helm_version:
        type: string 
        default: "3.4.0"
        required: false
      helm_chart:
        type: string
        default: '1.0.210'
        required: false
      gateway:
        type: string
        default: '1.0.210'
        required: false
      octopus_server_url:
        type: string
        required: true
      octopus_project_name:
        type: string
        description: "octopus project name"
        required: true
      dockerargs:
        type: string
        description: "Additional build arguments for docker, provided as a multiline string"
        required: false
      sonarqube_url:
        type: string
        description: "sonarqube url"
        required: true

    secrets:
      acr_username: 
        description: "service principal ID for azure ACR "
        required: true
      acr_password: 
        description: "password for service principal for azure ACR"
        required: true
      octopus_api_key:
        description: "api-key for octopus deploy"
        required: true      
      sonarqube_token:
        required: true
        description: "token for sonarqube"
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # defaults to "docker-containerized"      

      - name: Log in to Azure ACR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - name: Log in to Azure dev ACR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ inputs.registrydev }}
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ inputs.registry }}/${{inputs.image_name}}:${{inputs.version}}
          file: Dockerfile
          build-args: |
            SONARQUBE_URL=${{inputs.sonarqube_url}}
            SONARQUBE_PROJECT_NAME=${{inputs.image_name}}
            SONARQUBE_TOKEN=${{secrets.sonarqube_token}}
            SONARQUBE_VERSION=${{inputs.version}}
            ${{inputs.dockerargs}}
      
      - name: Retrieve Sonarqube scan status
        shell: bash
        id: sonarqube_scan_status
        run: |
          key=$(curl -s -q \
            -u ${{secrets.sonarqube_token}}: \
            "${{inputs.sonarqube_url}}/api/project_analyses/search?project=${{inputs.image_name}}" \
            | jq -r '.analyses[] | select(.projectVersion=="${{inputs.version}}") | .key')

          status=$(curl -s -q \
            -u ${{secrets.sonarqube_token}}: \
            "${{inputs.sonarqube_url}}/api/qualitygates/project_status?analysisId=$key" | jq -r '.projectStatus.status')
          
          echo "$status"
      
      - name: Update the Pull Request with the SonarQube scan result
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          status: "${{ steps.sonarqube_scan_status.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### SonarQube scan output 🖌\`${{ env.status }}\`

            <details><summary>Details</summary>

            [Project](${{inputs.sonarqube_url}}/dashboard?id=${{inputs.image_name}})

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  create-octopus-environment:
    runs-on: self-hosted
    name: Create an environment in Octopus Deploy
    
    steps:
    - name: Set environment name from branch name
      shell: python3 {0}
      run: |
        import re
        import os
       
        # strip the 'refs/heads/' from the branch name
        branch_name = os.environ["GITHUB_REF"].replace("refs/heads/", "")

        # keep letters and numbers
        pattern = "[^0-9a-zA-Z\s]+"

        # perform a regex substitution to clean the branch name 
        # from any charachers except letters and numbers
        sanitized_branch_name = re.sub(pattern, "", branch_name)

        print("##[set-output name=env;]test-"+sanitized_branch_name)
      id: set_environment_name

    - uses: planday-corp/create-octopus-environment@main
      with: 
          environment_name: "${{steps.set_environment_name.outputs.env}}"
          delete: false
          environment_to_copy: "stable"
          octopus_server_url: "${{inputs.octopus_server_url}}"
          octopus_api_key: ${{secrets.octopus_api_key}}
      
  create-deploy-release:
    name: Create a release in Octopus and deploy it to a dynamic environment
    runs-on: self-hosted
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') && ! contains('
        refs/heads/main
        refs/heads/master', github.ref) }}
    needs: [build-and-push]
    steps:
    - name: Set environment name from branch name
      shell: python3 {0}
      run: |
        import re
        import os
       
        # strip the 'refs/heads/' from the branch name
        branch_name = os.environ["GITHUB_REF"].replace("refs/heads/", "")

        # keep letters and numbers
        pattern = "[^0-9a-zA-Z\s]+"

        # perform a regex substitution to clean the branch name 
        # from any charachers except letters and numbers
        sanitized_branch_name = re.sub(pattern, "", branch_name)

        print("##[set-output name=env;]test-"+sanitized_branch_name)
      id: set_environment_name
    
    - name: Install Octopus CLI 🐙
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.10
    
    - name: Deploy release 🐙
      uses: OctopusDeploy/create-release-action@v1.1.1
      with:
        deploy_to: "${{steps.set_environment_name.outputs.env}}"
        api_key: ${{ secrets.octopus_api_key }}
        server: ${{ inputs.octopus_server_url }}
        space: 'Default'
        project: ${{ inputs.octopus_project_name }}
        release_number: ${{inputs.version}}
        progress: true
        packages: |
          ${{inputs.image_name}}:${{inputs.version}}
          helm:${{inputs.helm_version}}
          planday-service-istio:${{inputs.helm_chart}}
          certificate-and-gateway:${{inputs.gateway}}
      