name: Build and push helm package to azure acr

on:
  workflow_call:
    inputs:
      helm_name:
        type: string
        description: "Name of the helm package"
        required: true
      version:
        type: string
        description: "Version of helm package to build. (ex: '1.2.3' or 'v1.2.4)"
        required: true
      registry:
        type: string
        description: "Azure Containers Registry to push the package to"
        required: true
      

jobs:
  build-and-push:
    name: Build and push helm package to ACR
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Log in to Azure ACR
        run: |
          helm registry login ${{ inputs.registry }} --username ${{ secrets.acr_username }} --password ${{ secrets.acr_password }} 
      