name: Build and push helm package to azure acr

on:
  workflow_call:
    inputs:
      helm_name:
        type: string
        description: "Name of the helm package"
        required: true
      version:
        type: string
        description: "Version of helm package to build. (ex: '1.2.3' or 'v1.2.4)"
        required: true
      registry:
        type: string
        description: "Azure Containers Registry to push the package to"
        required: true
    secrets: 
      acr_username: 
        description: "Service Principal ID for Azure ACR"
        required: true
      acr_password: 
        description: "Service Principal password for Azure ACR"
        required: true
      

jobs:
  build-and-push:
    name: Build and push helm package to ACR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        id: install
        with:
          version: v3.10.0
      
      - name: Log in to Azure ACR
        run: |
          helm registry login ${{ inputs.registry }} --username ${{ secrets.acr_username }} --password ${{ secrets.acr_password }} 
      
      - name: Save chart locally
        run: |
          helm package ./ --version ${{ inputs.version }}
        
      - name: Push chart to ACR
        run: |
          helm push "./${{ inputs.helm_name }}-${{ inputs.version }}.tgz" "oci://${{ inputs.registry }}/helm"